### ISSUE TITLE
Set Plane Position

### ISSUE THREAD

**Issue by LittlePenguinNN** [gasgiant/Aircraft-Physics#14]
Hi, I want to assign a starting point to the plane in the `Start()` function in the `Airplanecontroller.cs` file. Simply the plane must start from a specific x,y,z point when the game starts. What changes do I need to make in the `Start()` function for this?

**Comment by ProximalElk6186** [comment]
Why? Just why?
Move the plane in the Unity Editor!

**Comment by LittlePenguinNN** [comment]
I want to navigate with Reinforcement Learning. Therefore, in each Reinforcement Learning episode, the aircraft must start from a different point.

**Comment by ProximalElk6186** [comment]
Maybe create a new game object, add a script to it. 
in script, add a “void Awake()” and “public transform Plane”. Add float values for the wanted x, y and z coords of the plane. 
Inside void Awake, make a Vector3 for both the plane  pos and the wanted pos. Then set plane’s pos to wanted pos. In editor, you’ll have a field on the newly added game object for plane and wanted coords.

**Comment by LittlePenguinNN** [comment]
```
using UnityEngine;

public class Deneme : MonoBehaviour
{
    public Transform plane;
    public float wantedX; 
    public float wantedY; 
    public float wantedZ; 

    void Awake()
    {
        if (plane != null)
        {

            Vector3 currentPos = plane.position;
            Vector3 wantedPos = new Vector3(wantedX, wantedY, wantedZ);
            plane.position = wantedPos;

            Debug.Log("Plane position set to: " + wantedPos);
        }
        else
        {
            Debug.LogError("Plane transform component is not assigned!");
        }
    }
}
```
I wrote a sample code, but it does not get the initial values ​​of the plane. Is there anything I might try differently?
I get the transform of the plane and the desired x, y, and z positions from the Unity interface.

**Comment by ProximalElk6186** [comment]
So, you press “Play” button in editor and the plane doesn’t move to where you specified it?

**Comment by LittlePenguinNN** [comment]
No, I want to start plane at a desired x,y and z position. When I press the "Play" button, plane must be start at desired x,y and z position. I don't want it to move the location that I specified when I press the "Play" button.

**Comment by ProximalElk6186** [comment]
And what’s bad with moving?

**Comment by ProximalElk6186** [comment]
Then sorry, I can’t help you with that

**Comment by ProximalElk6186** [comment]
Or maybe make different scenes for all of the positions you want

**Comment by LittlePenguinNN** [comment]
Okay, thanks I will try this.
