### ISSUE TITLE
Why are you using padded angles and how do you get the values?

### ISSUE THREAD

**Issue by BasNijhof** [gasgiant/Aircraft-Physics#2]
Hi, I like your project and I was looking into your code. When you calculate your aerodynamic coefficients you add padding your your stall angles. Why? And you determine the padding by lerping between 8 and 14 degrees, why 8 and 14, or did you guess these values a bit?

![image](https://user-images.githubusercontent.com/76704161/103237708-c0707300-4948-11eb-928a-fa50b0eee730.png)

**Comment by gasgiant** [comment]
Hi! So, the paper this repository is based on isn't clear on how they transition from low AoA to full-stall mode. Judging by their plots they basically end low AoA zone at stall angles and start fully stalled mode at some angle higher (or lower in case of negative AoA) than stall angle, which I called padded stall angle. The transition zone is just a straight line between the boundary values of the modes, as far as I can tell. The size of the transition zone varies with control surface deflection angle and I eyeballed it from the plots. 

Initially I tried to transition from low AoA to stall at exactly stall angle, but it lead to a way to sharp drop of lift when stall happens.  

Below are the plots I'm talking about. 
![image](https://user-images.githubusercontent.com/31007222/103259365-06bee400-49d4-11eb-9458-acde55fd3ef4.png)

**Comment by gasgiant** [comment]
Actually, looking at it again, I think the formula for padding I came up with is wrong. First of all padding is different for negative and positive angles of attack. So for example for large positive deflections padding is small for positive aoas and large for negative ones. Also the values of 8 and 14 seem wrong. I'll fix it later this week.

**Comment by BasNijhof** [comment]
Oh okay thank you! I have another question: Why do you need a prediction timestep fraction when you're predicting the velocity and the angular velocity? Because I thought the velocity you gain should just be Δtime * force / mass.

**Comment by gasgiant** [comment]
Explicit Euler integration (Δtime * force / mass) can work fine, but in certain cases requires very small delta time to be accurate and stable. This is because force is dependent on velocity and angular velocity. The equation above assumes that force is constant during the frame, while it is not the case. Usually it is a valid assumption, but sometimes it can lead to jitter. Predicting velocity and updating the force using these new values is a way to make integration more precise and stable.
