### ISSUE TITLE
Yaw fix?

### ISSUE THREAD

**Issue by alexandre-root** [gasgiant/Aircraft-Physics#5]
Hi! This physics is quite good, however, I can't turn with the yaw at low speed, on the ground. I have to reach a certain amount of speed to turn on the ground. And this amount of speed is quite significant. So I tried to multiply the yaw sensitivity. But It didn't work. I'm not familiar with Unity's wheel colliders but maybe the issue come from here? Does the wheel collider rotate with the yaw movment?

**Comment by alexandre-root** [comment]
Found this: https://docs.unity3d.com/ScriptReference/WheelCollider-steerAngle.html

**Comment by gasgiant** [comment]
Yaw control in the example plane simply doesn't control wheels, only the rudder. So naturally, you can only turn when you gain some airspeed. You can surely extend it to steer the wheels by using steerAngle of the wheel collider or other means.

**Comment by alexandre-root** [comment]
So, I added this:
```cs
frontWheelCollider.steerAngle = -Input.GetAxis("Yaw") * wheelSteerAngleMultiplier;
```

And it works pretty well! Fell free to add it to your code 😉. Planes are more agile on the ground than most people think!

**Comment by gasgiant** [comment]
The AirplaneController is not meant to be a feature-full plane controller, but rather an example of how to interact with the aerodynamics system. So I want to keep it as simple as possible.

**Comment by alexandre-root** [comment]
I see, np!
