### ISSUE TITLE
How combined aspect ratio is calculated?

### ISSUE THREAD

**Issue by Arugin** [gasgiant/Aircraft-Physics#9]
Hello!
So there are Wing_L_0 and Wing_L_1 stacked together, and the aspect ratio set to 7 for both. How this value is calculated, if I am doing something like this:

    (span1 + span2) / ((chord1 + chord2) / 2)

I get something like 3.5. But I think I am doing this wrong.

**Comment by gasgiant** [comment]
Wing_L_0 and Wing_L_1 are different aerosurfaces that are stacked together, as you noticed, to represent a single surface. Their chords are roughly the same and equal to, say `chord`. The the aspect ratio of this full surface is `chord / (span1 + span2)`.

**Comment by gasgiant** [comment]
I think your reasoning is correct. I might have considered the whole wing as a single surface and set the aspect ratio to 7. This is probably wrong and 3.5 is the correct number.

**Comment by Arugin** [comment]
Thanks, will try it out and will let you know what I found out.

**Comment by Arugin** [comment]
So I've tried 3.5 value, lift force is obviosly decreased a bit, but everything is working as expected. I have one more question.

I am not quite understanding why config.chord used in CalculateForces, in the line:

    Vector3 torque = -transform.forward * aerodynamicCoefficients.z * dynamicPressure * area * config.chord;

Where I can find a source formula for this?

**Comment by gasgiant** [comment]
I think it's just in the definition of the torque coefficient C_M. See for instance https://aerotoolbox.com/lift-drag-moment-coefficient/

**Comment by Arugin** [comment]
Thank you!
